all:
	@cd cffi_interfaces; $(MAKE)

CLEAN_DIRS += $(LIDT_ROOT)/src/app/processor/cffi_interfaces

PY_CACHE_CLEAN = __pycache__
#-----------------------------------------------------------------------------
include $(LIDT_MAKEDIR)/Makefile.app 