#-----------------------------------------------------------------------------
# Makefile - make/Makefile.gtest
#
# Copyright (c) Tien Nguyen Anh
#
# Modified History
# ----------------
#    Created: 2016-Dec-04 
#    Modified: 2016-Dec-07
#-----------------------------------------------------------------------------

ifndef  make_utest
make_utest = once_only

APP = unittest

#-----------------------------------------------------------------------------
LCOV = lcov
LCOV_BASEDIR=$(shell pwd)
GENHTML = genhtml
GCOVFLAGS = -fprofile-arcs -ftest-coverage

#-----------------------------------------------------------------------------
ifndef GTEST_ROOT
    GTEST_ROOT = /development/gtest-1.7
endif

UTTEST_INCS = -I $(GTEST_ROOT)/include -I ../
UTTEST_LIBS = -L$(GTEST_ROOT)/lib -lgtest_main -lgtest
REPORT_COVER_DIR = REPORT_COVERAGE

CLEAN += $(addprefix $(OBJ_DIR)/, *.gcda *.gcno *.o *.gcov)
CLEAN += *.bin *.info* *.xml log/*
CLEAN += $(REPORT_COVER_DIR)
#-----------------------------------------------------------------------------
TEST_SRCS_CPP = $(wildcard *.cpp)

TEST_OBJS = $(addprefix $(OBJ_DIR)/, $(TEST_SRCS_CPP:.cpp=.o))

TEST_BIN = gtest.bin

#-----------------------------------------------------------------------------
INCS += $(TEST_OBJECT) .

LIBS += $(UTTEST_LIBS) -lgcov -lpthread -lrt $(LIBS_BOOST)

INCLUDE_LIBS += $(UTTEST_INCS)
COMMON_FLAGS += $(GCOVFLAGS)

#-----------------------------------------------------------------------------
ut: all unittest
unittest: report_cover

#-----------------------------------------------------------------------------
test: $(TEST_BIN)

endif #once_only