#-------------------------------------------------------------------------------
# Makefile - make/Makefile.rules
#
# Copyright (c) Tien Anh Nguyen
#
# Modified history
# --------------------
#    Created: 2016-Dec-04 
#    Modified: 2016-Dec-07
#-------------------------------------------------------------------------------

ifndef  make_rules
make_rules = once_only

include $(LIDT_MAKEDIR)/Makefile.lidt

#-------------------------------------------------------------------------------
# Directory of objects

ifndef  OBJ_DIR
    OBJ_DIR = .
endif

TARGET_DIR = $(LIDT_ROOT)/runtime

#-------------------------------------------------------------------------------

RUN_TIME := $(TARGET_DIR)

ifdef ARCHIVE_ALT
    ADD_ARCHIVES := $(addsuffix _$(ARCHIVE_ALT), $(ARCHIVES))
    ARCHIVES += $(ADD_ARCHIVES)
endif

CLEAN   := $(CLEAN) $(OBJS)

OBJS    := $(addprefix  $(OBJ_DIR)/, $(OBJS))
SUBOBJS := $(addprefix  $(OBJ_DIR)/, $(SUBOBJS))
EXTOBJS := $(strip $(EXTOBJS))
CMNOBJS := $(strip $(CMNOBJS))

TARGET  := $(addprefix  $(TARGET_DIR)/, $(TARGET))
PROGRAM := $(addprefix $(RUN_TIME)/, $(PROGRAM))
ARCHIVES := $(addprefix  $(LIB_DIR)/, $(patsubst %, lib%.a, $(ARCHIVES)))
SUBDIRS := $(addprefix  $(PWD)/, $(SUBDIRS))
LIDT_LIBS := $(patsubst %, lib%.a, $(LIBRARY))
LIDT_LIBS_DIR := $(LIDT_ROOT)/obj/app/libs/
CLEAN   := $(CLEAN) $(OBJS)

#-------------------------------------------------------------------------------
INCLUDES = $(foreach i, $(INCS_DIRS), -I $(LIDT_ROOT)/$(i))

#-------------------------------------------------------------------------------
ifndef  TARGET
    ifeq ($(words $(PROGRAM)), 1)
        TARGET := $(PROGRAM)
    endif
endif

#-------------------------------------------------------------------------------
TARGET_CLEAN := $(TARGET)

#-------------------------------------------------------------------------------
ARCHIVES_CLEAN := $(ARCHIVES)

#-------------------------------------------------------------------------------
# Default action: build the list of targets in the correct order

.PHONY: all

all:    $(OBJS)

all:    $(LIDT_LIBS) $(LOCAL_TARGET) $(TARGET) $(PROGRAM) $(ARCHIVES)

ifdef CFFI_SRCS
all: $(CFFI_OBJS)
endif

#-------------------------------------------------------------------------------
# Compiler flags
ifdef USE_CPP_LANG
    LIBS += -lstdc++
endif

CC 		= gcc
CPP 	= g++
AR 		= ar

#----------------------------------------------------------------------------
ifdef TARGET
$(TARGET): $(OBJS) $(ARCHIVES) $(LIDT_LIBS)
	$(ECHO) "Linking " $@
	$(RM) $@;
	$(LD) $(strip $(filter %.o, $^) -L$(LIB_DIR) $(patsubst lib%.a, -l%, $(LIDT_LIBS)) $(LIBS) $(LIBS_BOOST) -o $@)
endif

#-------------------------------------------------------------------------------
#Compiling rules for CFFI
__cffi_%.pyc: __cffi_%.py
	$(ECHO) Compile CFFI interace $^
	$(PYTHON)  $^

#----------------------------------------------------------------------------
# Unittest

ifeq ($(APP),unittest)

report_xml: $(TEST_BIN)
	$(ECHO) 'Run test'
	./$^ $(LIBS) --gtest_output=xml

report_cover: report_xml
	$(ECHO) 'Generating UNITTEST_REPORT'
	$(LCOV) --capture -q -c -b $(LCOV_BASEDIR) -d $(OBJ_DIR) -o r.info.all
	@$(LCOV) --remove r.info.all "/usr*" -o r.info.all > /dev/null
	@$(LCOV) --remove r.info.all "gtest*" -o r.info.all > /dev/null
	@$(LCOV) --remove r.info.all "/development/*" -o r.info.all > /dev/null
	$(LCOV) -q -r r.info.all "*/test/*" -b $(LCOV_BASEDIR) -o r.info
	$(GENHTML) -q -o $(REPORT_COVER_DIR) --t VARBASE_TEST_RESULT r.info 
	$(LCOV) -q -z -b $(LCOV_BASEDIR) -d $(OBJ_DIR)

$(OBJ_DIR)/%.o:     ../%.c
	@$(ECHO) " Compiling " $< "for unittest"
	$(RM) $@;
	$(CC) -c $(COMMON_FLAGS) $< -o $@ $(LIBS) $(INCLUDES) $(INCLUDE_LIBS)

$(OBJ_DIR)/%.o:     ../%.cpp
	@$(ECHO) " Compiling " $<  "for unittest"
	$(RM) $@;
	$(CPP) -c $(COMMON_FLAGS) -std=c++11 $< -o $@ $(LIBS) $(INCLUDES) $(INCLUDE_LIBS)

gtest.bin: $(TEST_OBJS) $(OBJS)
	$(ECHO) " Linking " $@
	$(RM) $@
	$(CPP) $^ $(LIBS) -L$(LIB_DIR) -L$(LIDT_LIBS_DIR) $(patsubst lib%.a, -l%, $(filter %.a, $(LIDT_LIBS))) -o $@

CLEAN += $(OBJS)
endif

#------------------------------------------------------------------------------
# Compile rules:

$(OBJ_DIR)/%.o:     %.c
	$(ECHO) "Compiling to Object" $<
	$(RM) $@
	$(CC) $(COMMON_FLAGS) -c $< -o $@ $(LIBS) $(INCLUDES) $(INCLUDE_LIBS)

$(OBJ_DIR)/%.o:     %.cpp
	$(ECHO) "Compiling to Object" $<
	$(RM) $@
	$(CPP) -c $(COMMON_FLAGS) -std=c++11 $< -o $@ $(LIBS) $(INCLUDES) $(INCLUDE_LIBS)

$(LIB_DIR)/lib%_$(ARCHIVE_ALT).a: $(OBJS)
	$(ECHO) "Creating archive" $@
	$(AR) -cr $@ $^ $(LIBS)

$(LIB_DIR)/lib%.a: $(OBJS)
	$(ECHO) "Creating archive" $@
	$(AR) -cr $@ $^ $(SUBOBJS)

$(OBJ_DIR)/lib%.so:     %.o
	$(CC) -shared -o $@ $<

#-------------------------------------------------------------------------------
#Compile library
ifdef   LIBRARY
lib%.a: 
	$(ECHO) "Compiling library " $(LIBDIRS_$*)
	@cd $(LIBDIRS_$*); $(MAKE)
endif

#-------------------------------------------------------------------------------
# clean and clobber etc.

# CLEAN    += core
# CLEAN_DIRS += $(SUBDIRS)

include $(LIDT_MAKEDIR)/Makefile.clean

endif   # once_only
